# Generated by Django 4.0.6 on 2022-07-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_user_deleted_at_user_is_deleted'),
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.hotel'),
        ),
    ]
