# Generated by Django 4.0.6 on 2022-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_bookingrequest_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='picture',
            field=models.ImageField(default='payment_method.png', null=True, upload_to=''),
        ),
    ]
