# Generated by Django 4.0.6 on 2022-07-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_paid_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestedroom',
            options={},
        ),
    ]
