# Generated by Django 4.0.6 on 2022-08-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_requestedroom_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paid',
            unique_together={('booking_request', 'transaction_id')},
        ),
    ]
