# Generated by Django 4.0.6 on 2022-07-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinformation',
            old_name='pyment_method',
            new_name='payment_method',
        ),
    ]
