# Generated by Django 4.0.6 on 2022-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_pyment_method_paymentinformation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
