# Generated by Django 4.0.6 on 2022-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
